const express = require("express");
const registerApi = require("./register");
const loginApi = require("./login");
const getAllApi=require("./getall");
const getSingleUserApi=require("./getSingleUser");
const updateUserApi=require('./updateUser');
const deleteUserApi=require('./deleteUser');
const getUsageApi=require('./getUsage');
const uploadApi=require('./uploadDoc');
const combineApi=require('./combine');
const usageDetailsApi=require('./usageDetails');
const getCountApi=require('./getCount');
const invoiceApi=require('./invoice');
const postAllApi=require('./postAll');
const getDataApi=require('./getData');
const getSingle=require('./getSingle');
const usageApi=require('./usage');
const countUserApi=require("./countUser");
const totalUsageApi=require("./totalUsage");
const usagebyEmailApi=require("./usagebyEmail");
const { route } = require("./login");
const usagebyBuildingApi=require("./usagebyBuilding");
const totalUserUsageApi=require('./totalUserUsage');
const totalBuildingUsageApi=require("./totalBuildingUsage");
// const getExcelApi=require('./getExcel');
// const combineApi=require('./combine');
//const excelUploadApi=require('./excelUpload');
// const { route } = require("./register");

const router = express.Router();


router.use(registerApi);
router.use(loginApi);
router.use(getAllApi);
router.use(getSingleUserApi);
router.use(updateUserApi);
router.use(deleteUserApi);
router.use(usageApi);
router.use(getUsageApi);
router.use(uploadApi);
router.use(combineApi);
router.use(usageDetailsApi);
router.use(getCountApi);
router.use(invoiceApi);
router.use(postAllApi);
router.use(getDataApi);
router.use(getSingle);
router.use(countUserApi);
router.use(totalUsageApi);
router.use(usagebyEmailApi);
router.use(usagebyBuildingApi);
router.use(totalUserUsageApi);
router.use(totalBuildingUsageApi);
// router.use(getExcelApi);
//router.use(combineApi);
//router.use(excelUploadApi);

module.exports = router;
